#definimos el tipo de base de datos
quarkus.datasource.db-kind=postgresql

#usuario con el conecta a la base de datos
quarkus.datasource.username=postgres

#password del usuario de conexion
quarkus.datasource.password=deyvi

#url de la base datos
 quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pa2db

#sincronizar lo que tengo en codigo a la base datos
quarkus.hibernate-orm.database.generation=update

#se muestre en la consola de quarus en sql
quarkus.hibernate-orm.log.sql=true


#sincroniza el codigo a la dB
quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.log.sql=true
